// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SandboxSnapshotRef: core.serialization.ObjectSchema<
    serializers.SandboxSnapshotRef.Raw,
    TrueForge.SandboxSnapshotRef
> = core.serialization.object({
    digest: core.serialization.string(),
    image: core.serialization.string(),
    snapshotName: core.serialization.property("snapshot_name", core.serialization.string()),
});

export declare namespace SandboxSnapshotRef {
    export interface Raw {
        digest: string;
        image: string;
        snapshot_name: string;
    }
}
