// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SandboxSnapshotRef } from "./SandboxSnapshotRef.js";

export const SandboxSnapshotSync: core.serialization.ObjectSchema<
    serializers.SandboxSnapshotSync.Raw,
    TrueForge.SandboxSnapshotSync
> = core.serialization.object({
    active: SandboxSnapshotRef.optional(),
    desiredImage: core.serialization.property("desired_image", core.serialization.string()),
    errorMessage: core.serialization.property("error_message", core.serialization.string().optional()),
    pending: SandboxSnapshotRef.optional(),
    updatedAt: core.serialization.property("updated_at", core.serialization.date()),
});

export declare namespace SandboxSnapshotSync {
    export interface Raw {
        active?: SandboxSnapshotRef.Raw | null;
        desired_image: string;
        error_message?: string | null;
        pending?: SandboxSnapshotRef.Raw | null;
        updated_at: string;
    }
}
