// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface ConfiguredSandboxProvider {
    auth: TrueForge.DaytonaSandboxProviderAuth;
    autoArchiveIntervalInMinutes: number;
    autoDeleteIntervalInMinutes: number;
    autoStopIntervalInMinutes: number;
    /** Default sandbox command exec timeout in milliseconds. */
    execTimeoutMs: number;
    snapshotSync: TrueForge.SandboxSnapshotSync;
    type: "daytona";
}
