// This file was auto-generated by Fern from our API Definition.

export interface GetCapabilitiesResponseDataSandbox {
    /** Whether sandboxes can be created: a provider is configured and its sandbox image is synced to the provider. */
    enabled: boolean;
    /** Present when sandbox is disabled. Explains why. */
    reason?: string;
}
