// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../index.js";

export interface SandboxSnapshotSync {
    active?: TrueForge.SandboxSnapshotRef;
    desiredImage: string;
    errorMessage?: string;
    pending?: TrueForge.SandboxSnapshotRef;
    updatedAt: Date;
}
