// This file was auto-generated by Fern from our API Definition.

import * as TrueForgeTypes from "../../../src/api/index";
import { TrueForge } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SandboxProvidersClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: {
                auth: { api_key: "api_key" },
                auto_archive_interval_in_minutes: 1,
                auto_delete_interval_in_minutes: 1,
                auto_stop_interval_in_minutes: 1,
                exec_timeout_ms: 1,
                snapshot_sync: {
                    active: { digest: "digest", image: "image", snapshot_name: "snapshot_name" },
                    desired_image: "desired_image",
                    error_message: "error_message",
                    pending: { digest: "digest", image: "image", snapshot_name: "snapshot_name" },
                    updated_at: "2024-01-15T09:30:00Z",
                },
                type: "daytona",
            },
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/sandbox-providers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.sandboxProviders.get();
        expect(response).toEqual({
            data: {
                auth: {
                    apiKey: "api_key",
                },
                autoArchiveIntervalInMinutes: 1,
                autoDeleteIntervalInMinutes: 1,
                autoStopIntervalInMinutes: 1,
                execTimeoutMs: 1,
                snapshotSync: {
                    active: {
                        digest: "digest",
                        image: "image",
                        snapshotName: "snapshot_name",
                    },
                    desiredImage: "desired_image",
                    errorMessage: "error_message",
                    pending: {
                        digest: "digest",
                        image: "image",
                        snapshotName: "snapshot_name",
                    },
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
                type: "daytona",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .get("/api/v1/settings/sandbox-providers")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.sandboxProviders.get();
        }).rejects.toThrow(TrueForgeTypes.NotFoundError);
    });

    test("upsert (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = {
            auth: { api_key: "api_key" },
            auto_archive_interval_in_minutes: 1,
            auto_delete_interval_in_minutes: 1,
            auto_stop_interval_in_minutes: 1,
            exec_timeout_ms: 1,
            type: "daytona",
        };
        const rawResponseBody = {
            data: {
                auth: { api_key: "api_key" },
                auto_archive_interval_in_minutes: 1,
                auto_delete_interval_in_minutes: 1,
                auto_stop_interval_in_minutes: 1,
                exec_timeout_ms: 1,
                snapshot_sync: {
                    active: { digest: "digest", image: "image", snapshot_name: "snapshot_name" },
                    desired_image: "desired_image",
                    error_message: "error_message",
                    pending: { digest: "digest", image: "image", snapshot_name: "snapshot_name" },
                    updated_at: "2024-01-15T09:30:00Z",
                },
                type: "daytona",
            },
        };

        server
            .mockEndpoint()
            .put("/api/v1/settings/sandbox-providers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.sandboxProviders.upsert({
            auth: {
                apiKey: "api_key",
            },
            autoArchiveIntervalInMinutes: 1,
            autoDeleteIntervalInMinutes: 1,
            autoStopIntervalInMinutes: 1,
            execTimeoutMs: 1,
        });
        expect(response).toEqual({
            data: {
                auth: {
                    apiKey: "api_key",
                },
                autoArchiveIntervalInMinutes: 1,
                autoDeleteIntervalInMinutes: 1,
                autoStopIntervalInMinutes: 1,
                execTimeoutMs: 1,
                snapshotSync: {
                    active: {
                        digest: "digest",
                        image: "image",
                        snapshotName: "snapshot_name",
                    },
                    desiredImage: "desired_image",
                    errorMessage: "error_message",
                    pending: {
                        digest: "digest",
                        image: "image",
                        snapshotName: "snapshot_name",
                    },
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
                type: "daytona",
            },
        });
    });

    test("upsert (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = {
            auth: { api_key: "x" },
            auto_archive_interval_in_minutes: 1,
            auto_delete_interval_in_minutes: 1,
            auto_stop_interval_in_minutes: 1,
            exec_timeout_ms: 1,
            type: "daytona",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/settings/sandbox-providers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.sandboxProviders.upsert({
                auth: {
                    apiKey: "x",
                },
                autoArchiveIntervalInMinutes: 1,
                autoDeleteIntervalInMinutes: 1,
                autoStopIntervalInMinutes: 1,
                execTimeoutMs: 1,
            });
        }).rejects.toThrow(TrueForgeTypes.BadRequestError);
    });

    test("upsert (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });
        const rawRequestBody = {
            auth: { api_key: "x" },
            auto_archive_interval_in_minutes: 1,
            auto_delete_interval_in_minutes: 1,
            auto_stop_interval_in_minutes: 1,
            exec_timeout_ms: 1,
            type: "daytona",
        };
        const rawResponseBody = { error: { message: "message" } };

        server
            .mockEndpoint()
            .put("/api/v1/settings/sandbox-providers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.settings.sandboxProviders.upsert({
                auth: {
                    apiKey: "x",
                },
                autoArchiveIntervalInMinutes: 1,
                autoDeleteIntervalInMinutes: 1,
                autoStopIntervalInMinutes: 1,
                execTimeoutMs: 1,
            });
        }).rejects.toThrow(TrueForgeTypes.UnprocessableEntityError);
    });

    test("catalog", async () => {
        const server = mockServerPool.createServer();
        const client = new TrueForge({ maxRetries: 0, baseUrl: server.baseUrl });

        const rawResponseBody = {
            data: [
                {
                    auto_archive_interval_in_minutes: 1,
                    auto_delete_interval_in_minutes: 1,
                    auto_stop_interval_in_minutes: 1,
                    exec_timeout_ms: 1,
                    type: "daytona",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/api/v1/settings/sandbox-providers/catalog")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.settings.sandboxProviders.catalog();
        expect(response).toEqual({
            data: [
                {
                    autoArchiveIntervalInMinutes: 1,
                    autoDeleteIntervalInMinutes: 1,
                    autoStopIntervalInMinutes: 1,
                    execTimeoutMs: 1,
                    type: "daytona",
                },
            ],
        });
    });
});
