// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { DaytonaSandboxProviderAuth } from "../../../../../../types/DaytonaSandboxProviderAuth.js";

export const DaytonaSandboxProvider: core.serialization.Schema<
    serializers.settings.DaytonaSandboxProvider.Raw,
    TrueForge.settings.DaytonaSandboxProvider
> = core.serialization.object({
    auth: DaytonaSandboxProviderAuth,
    autoArchiveIntervalInMinutes: core.serialization.property(
        "auto_archive_interval_in_minutes",
        core.serialization.number(),
    ),
    autoDeleteIntervalInMinutes: core.serialization.property(
        "auto_delete_interval_in_minutes",
        core.serialization.number(),
    ),
    autoStopIntervalInMinutes: core.serialization.property(
        "auto_stop_interval_in_minutes",
        core.serialization.number(),
    ),
    execTimeoutMs: core.serialization.property("exec_timeout_ms", core.serialization.number()),
});

export declare namespace DaytonaSandboxProvider {
    export interface Raw {
        auth: DaytonaSandboxProviderAuth.Raw;
        auto_archive_interval_in_minutes: number;
        auto_delete_interval_in_minutes: number;
        auto_stop_interval_in_minutes: number;
        exec_timeout_ms: number;
    }
}
