// This file was auto-generated by Fern from our API Definition.

import type * as TrueForge from "../../../../../../index.js";

/**
 * @example
 *     {
 *         auth: {
 *             apiKey: "api_key"
 *         },
 *         autoArchiveIntervalInMinutes: 1,
 *         autoDeleteIntervalInMinutes: 1,
 *         autoStopIntervalInMinutes: 1,
 *         execTimeoutMs: 1
 *     }
 */
export interface DaytonaSandboxProvider {
    auth: TrueForge.DaytonaSandboxProviderAuth;
    autoArchiveIntervalInMinutes: number;
    autoDeleteIntervalInMinutes: number;
    autoStopIntervalInMinutes: number;
    /** Default sandbox command exec timeout in milliseconds. */
    execTimeoutMs: number;
}
