{{- if not .Values.server.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harness.server.fullname" . }}
  labels:
    {{- include "harness.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  {{- range $key, $value := .Values.server.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
