apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harness.server.fullname" . }}
  labels:
    {{- include "harness.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
data:
  {{- range $key, $value := .Values.server.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
